function funElectionData() {
    const contAddData = document.getElementById('contAddData');
    const contElectionData = document.createElement('div') ;
        contElectionData.className = 'contElectionData' ;
        contAddData.appendChild(contElectionData) ;
    const btnAddCal = document.createElement('button') ;
        btnAddCal.className = 'btnAdd' ;
        btnAddCal.innerHTML = "Add Califications" ;
        contElectionData.appendChild(btnAddCal) ;
        const imgAddCal = document.createElement('img') ;
            imgAddCal.className = 'imgAdd' ;
            imgAddCal.src = imgcalifications ;
            btnAddCal.appendChild(imgAddCal) ;
    const btnAddExa = document.createElement('button'); ;
        btnAddExa.className = 'btnAdd' ;
        btnAddExa.innerHTML = "Add Examn" ;
        contElectionData.appendChild(btnAddExa) ;
        const imgAddExa = document.createElement('img') ;
            imgAddExa.className = 'imgAdd' ;
            imgAddExa.src = imgcalifications ;
            btnAddExa.appendChild(imgAddExa) ;
    const btnAddHW = document.createElement('button') ;
        btnAddHW.className = 'btnAdd' ;
        btnAddHW.innerHTML = "Add HomeWork" ;
        contElectionData.appendChild(btnAddHW) ;
        const imgAddHW = document.createElement('img') ;
            imgAddHW.className = 'imgAdd' ;
            imgAddHW.src = imgcalifications ;
            btnAddHW.appendChild(imgAddHW) ;
    const btnAddNotes = document.createElement('button') ;
        btnAddNotes.className = 'btnAdd' ;
        btnAddNotes.innerHTML = "Add Notes" ;
        contElectionData.appendChild(btnAddNotes) ;
        const imgAddNotes = document.createElement('img') ;
            imgAddNotes.className = "imgAdd" ;
            imgAddNotes.src = imgcalifications ;
            btnAddNotes.appendChild(imgAddNotes) ;
    const btnAddMeet = document.createElement('button') ;
        btnAddMeet.className = 'btnAdd' ;
        btnAddMeet.innerHTML = "Add Meeting" ;
        contElectionData.appendChild(btnAddMeet) ;
        const imgAddMeet = document.createElement('img') ;
            imgAddMeet.className = 'imgAdd' ;
            imgAddMeet.src = imgcalifications ;
            btnAddMeet.appendChild(imgAddMeet) ;
    const btnAddAct = document.createElement('button') ;
        btnAddAct.className = 'btnAdd' ;
        btnAddAct.innerHTML = "Add Activity" ;
        contElectionData.appendChild(btnAddAct) ;
        const imgAddAct = document.createElement('img') ;
            imgAddAct.className = 'imgAdd' ;
            imgAddAct.src = imgcalifications ;
            btnAddAct.appendChild(imgAddAct) ;
    const btnAddMon = document.createElement('button') ;
        btnAddMon.className = 'btnAdd' ;
        btnAddMon.innerHTML = "Add Money" ;
        contElectionData.appendChild(btnAddMon) ;
        const imgAddMon = document.createElement('img') ;
            imgAddMon.className = 'imgAdd' ;
            imgAddMon.src = imgcalifications ;
            btnAddMon.appendChild(imgAddMon) ;

    btnAddCal.addEventListener( 'click', ()=>{
        contElectionData.remove();
        const contFormCal = document.createElement('div') ;
            contFormCal.className = 'contFormCal' ;
            contAddData.appendChild(contFormCal) ;
            const inpCalNameStudent = document.createElement('input') ;
                inpCalNameStudent.className = 'inpForm' ;
                inpCalNameStudent.placeholder = "Name Student" ;
                contFormCal.appendChild(inpCalNameStudent) ;
            const inpCalification = document.createElement('input') ;
                inpCalification.className = 'inpForm' ;
                inpCalification.placeholder = "Calification Student" ;
                contFormCal.appendChild(inpCalification) ;
            const inpCalReviw = document.createElement('input') ;
                inpCalReviw.className = 'inpReviw' ;
                inpCalReviw.placeholder = "Add Student Reviw" ;
                contFormCal.appendChild(inpCalReviw) ;
            const btnCalPush = document.createElement('button') ;
                btnCalPush.className = 'btnPush' ;
                btnCalPush.innerHTML = "Push Calification" ;
                contFormCal.appendChild(btnCalPush) ;
    })

    btnAddExa.addEventListener('click', ()=>{
        contElectionData.remove() ;
        const contFormExa = document.createElement('div') ;
            contFormExa.className = 'contFormExa' ;
            contAddData.appendChild(contFormExa) ;
            const inpExaSubject = document.createElement('input') ;
                inpExaSubject.className = 'inputForm' ;
                inpExaSubject.placeholder = "Election Subject" ;
                contFormExa.appendChild(inpExaSubject) ;
            const inpExaDate = document.createElement('input') ;
                inpExaDate.className = 'inputForm' ;
                inpExaDate.type = 'date' ;
                contFormExa.appendChild(inpExaDate) ;
            const inpExaReviw = document.createElement('input') ;
                inpExaReviw.className = 'inputForm' ;
                inpExaReviw.type = 'text' ;
                inpExaReviw.placeholder = "Add You Reviw For Examn" ;
                contFormExa.appendChild(inpExaReviw) ;
            const btnExaPush = document.createElement('button') ;
                btnExaPush.className = 'btnPush' ;
                btnExaPush.innerHTML = "Push Examn" ;
                contFormExa.appendChild(btnExaPush) ;
                
    })
}